import { useMemo, useState, type ReactNode } from "react";
import { DEMO_PROMPT } from "./lib/constants";
import { generateRule, maskPrompt, previewRule, runSafeReview, scanPrompt } from "./lib/apiClient";
import type {
  ApplyScope,
  Finding,
  Rule,
  RuleGenerationResponse,
  RulePreviewResponse,
  SafeReviewResponse,
  TransformDepth,
  TransformMode
} from "./lib/types";

type TransformChoice = {
  mode: TransformMode;
  depth: TransformDepth;
  scope: ApplyScope;
};

const DEFAULT_CHOICE: TransformChoice = {
  mode: "placeholder",
  depth: "full",
  scope: "selected"
};

export default function App() {
  const [text, setText] = useState(DEMO_PROMPT);
  const [findings, setFindings] = useState<Finding[]>([]);
  const [selectedFindingId, setSelectedFindingId] = useState<string | null>(null);
  const [choices, setChoices] = useState<Record<string, TransformChoice>>({});
  const [globalChoice, setGlobalChoice] = useState<TransformChoice>({ ...DEFAULT_CHOICE, scope: "all" });
  const [ignoredFindingIds, setIgnoredFindingIds] = useState<string[]>([]);
  const [review, setReview] = useState<SafeReviewResponse | null>(null);
  const [status, setStatus] = useState("프롬프트를 붙여넣고 Scan을 눌러보세요.");
  const [customRules, setCustomRules] = useState<Rule[]>([]);
  const [ruleExample, setRuleExample] = useState("우리 회사 티켓 번호는 DEMO-2026-0001 형식입니다.");
  const [generatedRule, setGeneratedRule] = useState<RuleGenerationResponse | null>(null);
  const [rulePreview, setRulePreview] = useState<RulePreviewResponse | null>(null);

  const pendingFindings = findings.filter((finding) => !ignoredFindingIds.includes(finding.id));
  const selectedFinding = findings.find((finding) => finding.id === selectedFindingId) ?? findings[0];

  const findingChoices = useMemo(() => {
    return findings.reduce<Record<string, TransformChoice>>((acc, finding) => {
      acc[finding.id] = choices[finding.id] ?? {
        mode: finding.suggestedTransform.mode,
        depth: finding.suggestedTransform.depth ?? "full",
        scope: "selected"
      };
      return acc;
    }, {});
  }, [choices, findings]);

  async function handleScan() {
    const result = await scanPrompt({ text, customRules });
    setFindings(result.findings);
    setSelectedFindingId(result.findings[0]?.id ?? null);
    setIgnoredFindingIds([]);
    setReview(null);
    setStatus(result.findings.length > 0 ? `총 ${result.findings.length}개의 위험 요소를 찾았습니다.` : "탐지된 위험 요소가 없습니다.");
  }

  async function handleApply(finding: Finding) {
    const choice = findingChoices[finding.id] ?? DEFAULT_CHOICE;
    const result = await maskPrompt({
      text,
      findings,
      findingIds: [finding.id],
      mode: choice.mode,
      depth: choice.mode === "placeholder" ? undefined : choice.depth,
      scope: choice.scope
      , customRules
    });
    applyMaskResult(result.transformedText, result.findings, result.applied.length);
  }

  async function handleApplyAll() {
    const result = await maskPrompt({
      text,
      findings: pendingFindings,
      mode: globalChoice.mode,
      depth: globalChoice.mode === "placeholder" ? undefined : globalChoice.depth,
      scope: "all"
      , customRules
    });
    applyMaskResult(result.transformedText, result.findings, result.applied.length);
  }

  function handleIgnore(finding: Finding) {
    setIgnoredFindingIds((current) => [...new Set([...current, finding.id])]);
    setStatus("무시한 항목은 원본 값이 그대로 남습니다.");
  }

  async function handleSafeReview() {
    const response = await runSafeReview({
      transformedText: text,
      findings,
      applied: [],
      ignoredCount: ignoredFindingIds.length,
      ignoredTypes: findings.filter((finding) => ignoredFindingIds.includes(finding.id)).map((finding) => finding.type)
    });
    setReview(response);
    setStatus("Safe Review가 완료되었습니다.");
  }

  async function handleCopy() {
    await navigator.clipboard.writeText(text);
    setStatus("복사되었습니다. 이제 안전한 프롬프트를 AI 도구에 붙여넣을 수 있습니다.");
  }

  async function handleGenerateRule() {
    const response = await generateRule({ exampleText: ruleExample });
    setGeneratedRule(response);
    setRulePreview(null);
    setStatus(`Rule candidate generated by ${response.source}.`);
  }

  async function handlePreviewRule() {
    if (!generatedRule) return;
    const sampleText = generatedRule.tests[0]?.input ?? ruleExample;
    const response = await previewRule({ rule: generatedRule.rule, sampleText });
    setRulePreview(response);
    setStatus(response.matched ? "Rule preview matched sample text." : "Rule preview did not match sample text.");
  }

  function handleApproveRule() {
    if (!generatedRule) return;
    setCustomRules((current) => [...current.filter((rule) => rule.id !== generatedRule.rule.id), generatedRule.rule]);
    setStatus("Custom rule이 현재 세션에 추가되었습니다. Scan을 다시 실행해보세요.");
  }

  function applyMaskResult(transformedText: string, refreshedFindings: Finding[], appliedCount: number) {
    setText(transformedText);
    setFindings(refreshedFindings);
    setSelectedFindingId(refreshedFindings[0]?.id ?? null);
    setIgnoredFindingIds([]);
    setReview(null);
    setStatus(`${appliedCount}개 항목을 적용했습니다.`);
  }

  function updateChoice(findingId: string, patch: Partial<TransformChoice>) {
    setChoices((current) => ({
      ...current,
      [findingId]: { ...(findingChoices[findingId] ?? DEFAULT_CHOICE), ...patch }
    }));
  }

  return (
    <main className="app-shell">
      <header className="app-header">
        <div>
          <p className="eyebrow">Prompt safety preflight</p>
          <h1>Safe Prompt Guard</h1>
          <p>AI에게 보내기 전에 민감정보를 먼저 정리하세요.</p>
        </div>
        <p className="trust-note">원본 프롬프트는 AI 모델에 전송되지 않습니다.</p>
      </header>

      <section className="global-fix-bar" aria-label="Global fix bar">
        <strong>{findings.length > 0 ? `총 ${findings.length}개 위험 요소 발견` : "Scan 대기 중"}</strong>
        <select
          data-testid="global-mode-select"
          value={globalChoice.mode}
          onChange={(event) => setGlobalChoice((current) => ({ ...current, mode: event.target.value as TransformMode }))}
        >
          <option value="masking">마스킹</option>
          <option value="dummy">더미데이터</option>
          <option value="placeholder">플레이스홀더</option>
        </select>
        {globalChoice.mode !== "placeholder" && (
          <select
            data-testid="global-depth-select"
            value={globalChoice.depth}
            onChange={(event) => setGlobalChoice((current) => ({ ...current, depth: event.target.value as TransformDepth }))}
          >
            <option value="partial">부분 변경</option>
            <option value="full">전체 변경</option>
          </select>
        )}
        <button type="button" data-testid="scan-button" onClick={handleScan}>Scan</button>
        <button type="button" data-testid="apply-all-button" onClick={handleApplyAll} disabled={pendingFindings.length === 0}>모두 적용</button>
      </section>

      <section className="workspace" aria-label="Prompt guard workspace">
        <div className="editor-panel">
          <label htmlFor="prompt-input">Prompt</label>
          <textarea id="prompt-input" data-testid="prompt-input" value={text} onChange={(event) => setText(event.target.value)} />
          <div className="highlight-preview" aria-label="Highlight preview">
            {renderHighlightedText(text, findings, selectedFinding?.id ?? null, setSelectedFindingId, ignoredFindingIds)}
          </div>
        </div>

        <aside className="findings-panel" aria-label="Findings panel">
          <h2>Findings</h2>
          {findings.length === 0 && <p>탐지된 위험 요소가 없습니다.</p>}
          {findings.map((finding) => {
            const choice = findingChoices[finding.id] ?? DEFAULT_CHOICE;
            const ignored = ignoredFindingIds.includes(finding.id);
            return (
              <article className={`finding-card ${selectedFindingId === finding.id ? "selected" : ""}`} key={finding.id}>
                <div className="finding-card-header">
                  <span className={`severity ${finding.severity}`}>{finding.severity}</span>
                  <strong>{finding.type}</strong>
                </div>
                <p>{finding.reason}</p>
                <code>{finding.value}</code>
                <div className="control-row">
                  <select value={choice.mode} onChange={(event) => updateChoice(finding.id, { mode: event.target.value as TransformMode })}>
                    <option value="masking">마스킹</option>
                    <option value="dummy">더미데이터</option>
                    <option value="placeholder">플레이스홀더</option>
                  </select>
                  {choice.mode !== "placeholder" && (
                    <select value={choice.depth} onChange={(event) => updateChoice(finding.id, { depth: event.target.value as TransformDepth })}>
                      <option value="partial">부분</option>
                      <option value="full">전체</option>
                    </select>
                  )}
                  <select value={choice.scope} onChange={(event) => updateChoice(finding.id, { scope: event.target.value as ApplyScope })}>
                    <option value="selected">이 항목만</option>
                    <option value="same_type">같은 타입 전체</option>
                    <option value="all">모든 위험 요소</option>
                  </select>
                </div>
                <div className="button-row">
                  <button type="button" data-testid={`finding-${finding.id}-apply-button`} onClick={() => handleApply(finding)} disabled={ignored}>적용</button>
                  <button type="button" data-testid={`finding-${finding.id}-ignore-button`} onClick={() => handleIgnore(finding)} disabled={ignored}>무시</button>
                </div>
              </article>
            );
          })}
        </aside>
      </section>

      <section className="output-panel" aria-label="Safe output preview">
        <div>
          <h2>Safe Output Preview</h2>
          <pre>{text}</pre>
          <p className="status-line">{status}</p>
        </div>
        <div className="review-panel">
          <div className="button-row">
            <button type="button" data-testid="safe-review-button" onClick={handleSafeReview}>Safe Review</button>
            <button type="button" data-testid="copy-output-button" onClick={handleCopy}>Copy</button>
          </div>
          {review && (
            <div className="review-result">
              <strong>Safe Review: {review.riskLevel}</strong>
              <p>{review.summary}</p>
              <ul>
                {review.remainingConcerns.map((concern) => <li key={concern}>{concern}</li>)}
              </ul>
              <p>{review.recommendation}</p>
            </div>
          )}
        </div>
      </section>

      <section className="rule-builder-panel" aria-label="Custom rule builder">
        <div>
          <p className="eyebrow">Custom Rule Builder</p>
          <h2>조직별 패턴 추가</h2>
          <p className="trust-note">실제 secret이나 고객정보를 입력하지 마세요. 형식만 비슷한 더미 예시를 사용하세요.</p>
          <textarea
            data-testid="rule-builder-example-input"
            value={ruleExample}
            onChange={(event) => setRuleExample(event.target.value)}
            aria-label="Rule builder dummy example"
          />
          <div className="button-row">
            <button type="button" data-testid="rule-generate-button" onClick={handleGenerateRule}>Generate Rule</button>
            <button type="button" data-testid="rule-preview-button" onClick={handlePreviewRule} disabled={!generatedRule}>Preview</button>
            <button type="button" data-testid="rule-approve-button" onClick={handleApproveRule} disabled={!generatedRule}>세션에 추가</button>
          </div>
        </div>
        <div className="rule-preview-card">
          <h3>Rule Preview</h3>
          {generatedRule ? (
            <>
              <dl>
                <dt>type</dt>
                <dd>{generatedRule.rule.type}</dd>
                <dt>pattern</dt>
                <dd><code>{generatedRule.rule.pattern}</code></dd>
                <dt>replacement</dt>
                <dd><code>{generatedRule.rule.replacement}</code></dd>
                <dt>source</dt>
                <dd>{generatedRule.source}</dd>
              </dl>
              {generatedRule.warnings.map((warning) => <p className="warning" key={warning}>{warning}</p>)}
              <p>{generatedRule.falsePositiveRisk}</p>
              <p>{generatedRule.falseNegativeRisk}</p>
              {rulePreview && (
                <div className="review-result">
                  <strong>{rulePreview.matched ? "Matched" : "No match"}</strong>
                  <pre>{rulePreview.transformedText}</pre>
                </div>
              )}
              <p className="status-line">Session custom rules: {customRules.length}</p>
            </>
          ) : (
            <p>더미 예시로 rule 후보를 생성하세요.</p>
          )}
        </div>
      </section>
    </main>
  );
}

function renderHighlightedText(
  text: string,
  findings: Finding[],
  selectedFindingId: string | null,
  onSelect: (findingId: string) => void,
  ignoredFindingIds: string[]
) {
  if (findings.length === 0) return <span>{text}</span>;

  const nodes: ReactNode[] = [];
  let cursor = 0;

  findings.forEach((finding) => {
    if (cursor < finding.start) {
      nodes.push(<span key={`text-${cursor}`}>{text.slice(cursor, finding.start)}</span>);
    }
    nodes.push(
      <button
        type="button"
        key={finding.id}
        className={`highlight ${finding.severity} ${selectedFindingId === finding.id ? "selected" : ""} ${ignoredFindingIds.includes(finding.id) ? "ignored" : ""}`}
        onClick={() => onSelect(finding.id)}
      >
        {text.slice(finding.start, finding.end)}
      </button>
    );
    cursor = finding.end;
  });

  if (cursor < text.length) {
    nodes.push(<span key={`text-${cursor}`}>{text.slice(cursor)}</span>);
  }

  return nodes;
}