import { useMemo, useState, type ReactNode } from "react";
import { DEMO_PROMPT } from "./lib/constants";
import { generateRule, previewRule, runSafeReview, scanPrompt } from "./lib/apiClient";
import { composeSafeOutput, getFindingDisplayValue, getScopedFindingIds, type AppliedTransformChoice } from "./lib/output";
import type {
  ApplyScope,
  Finding,
  Rule,
  RuleGenerationResponse,
  RulePreviewResponse,
  SafeReviewResponse,
  TransformDepth,
  TransformMode
} from "./lib/types";

type TransformChoice = {
  mode: TransformMode;
  depth: TransformDepth;
  scope: ApplyScope;
};

type WorkspaceTab = "prompt" | "rules";

const DEFAULT_CHOICE: TransformChoice = {
  mode: "placeholder",
  depth: "full",
  scope: "selected"
};

export default function App() {
  const [activeTab, setActiveTab] = useState<WorkspaceTab>("prompt");
  const [sourceText, setSourceText] = useState(DEMO_PROMPT);
  const [findings, setFindings] = useState<Finding[]>([]);
  const [selectedFindingId, setSelectedFindingId] = useState<string | null>(null);
  const [choices, setChoices] = useState<Record<string, TransformChoice>>({});
  const [appliedChoices, setAppliedChoices] = useState<Record<string, AppliedTransformChoice>>({});
  const [globalChoice, setGlobalChoice] = useState<TransformChoice>({ ...DEFAULT_CHOICE, scope: "all" });
  const [ignoredFindingIds, setIgnoredFindingIds] = useState<string[]>([]);
  const [review, setReview] = useState<SafeReviewResponse | null>(null);
  const [status, setStatus] = useState("프롬프트를 붙여넣고 Scan을 눌러보세요.");
  const [customRules, setCustomRules] = useState<Rule[]>([]);
  const [ruleExample, setRuleExample] = useState("우리 회사 티켓 번호는 DEMO-2026-0001 형식입니다.");
  const [generatedRule, setGeneratedRule] = useState<RuleGenerationResponse | null>(null);
  const [rulePreview, setRulePreview] = useState<RulePreviewResponse | null>(null);

  const safeOutput = useMemo(() => composeSafeOutput(sourceText, findings, appliedChoices), [appliedChoices, findings, sourceText]);
  const pendingFindings = findings.filter((finding) => !ignoredFindingIds.includes(finding.id) && !appliedChoices[finding.id]);
  const selectedFinding = findings.find((finding) => finding.id === selectedFindingId) ?? findings[0];

  const findingChoices = useMemo(() => {
    return findings.reduce<Record<string, TransformChoice>>((acc, finding) => {
      acc[finding.id] = choices[finding.id] ?? {
        mode: finding.suggestedTransform.mode,
        depth: finding.suggestedTransform.depth ?? "full",
        scope: "selected"
      };
      return acc;
    }, {});
  }, [choices, findings]);

  async function handleScan() {
    const result = await scanPrompt({ text: sourceText, customRules });
    setFindings(result.findings);
    setSelectedFindingId(result.findings[0]?.id ?? null);
    setIgnoredFindingIds([]);
    setAppliedChoices({});
    setReview(null);
    setStatus(result.findings.length > 0 ? `총 ${result.findings.length}개의 위험 요소를 찾았습니다.` : "탐지된 위험 요소가 없습니다.");
  }

  function handleApply(finding: Finding) {
    const choice = findingChoices[finding.id] ?? DEFAULT_CHOICE;
    applyChoicesForFindings(getScopedFindingIds(findings, finding.id, choice.scope), choice);
  }

  function handleApplyAll() {
    applyChoicesForFindings(pendingFindings.map((finding) => finding.id), globalChoice);
  }

  function handleIgnore(finding: Finding) {
    setIgnoredFindingIds((current) => [...new Set([...current, finding.id])]);
    setAppliedChoices((current) => {
      const next = { ...current };
      delete next[finding.id];
      return next;
    });
    setReview(null);
    setStatus("무시한 항목은 원본 값이 그대로 남습니다.");
  }

  async function handleSafeReview() {
    const response = await runSafeReview({
      transformedText: safeOutput,
      findings,
      applied: Object.entries(appliedChoices).map(([findingId, choice]) => ({
        findingId,
        originalValue: findings.find((finding) => finding.id === findingId)?.value ?? "",
        transformedValue: "",
        mode: choice.mode,
        depth: choice.depth
      })),
      ignoredCount: ignoredFindingIds.length,
      ignoredTypes: findings.filter((finding) => ignoredFindingIds.includes(finding.id)).map((finding) => finding.type)
    });
    setReview(response);
    setStatus("Safe Review가 완료되었습니다.");
  }

  async function handleCopy() {
    await navigator.clipboard.writeText(safeOutput);
    setStatus("복사되었습니다. 이제 안전한 프롬프트를 AI 도구에 붙여넣을 수 있습니다.");
  }

  async function handleGenerateRule() {
    const response = await generateRule({ exampleText: ruleExample });
    setGeneratedRule(response);
    setRulePreview(null);
    setStatus(`Rule candidate generated by ${response.source}.`);
  }

  async function handlePreviewRule() {
    if (!generatedRule) return;
    const sampleText = generatedRule.tests[0]?.input ?? ruleExample;
    const response = await previewRule({ rule: generatedRule.rule, sampleText });
    setRulePreview(response);
    setStatus(response.matched ? "Rule preview matched sample text." : "Rule preview did not match sample text.");
  }

  function handleApproveRule() {
    if (!generatedRule) return;
    setCustomRules((current) => [...current.filter((rule) => rule.id !== generatedRule.rule.id), generatedRule.rule]);
    setStatus("Custom rule이 현재 세션에 추가되었습니다. Scan을 다시 실행해보세요.");
  }

  function handleSourceTextChange(nextText: string) {
    setSourceText(nextText);
    setFindings([]);
    setSelectedFindingId(null);
    setIgnoredFindingIds([]);
    setAppliedChoices({});
    setChoices({});
    setReview(null);
    setStatus("프롬프트가 변경되었습니다. 다시 Scan을 실행하세요.");
  }

  function applyChoicesForFindings(findingIds: string[], choice: TransformChoice) {
    const ignoredIds = new Set(ignoredFindingIds);
    const targetIds = findingIds.filter((findingId) => !ignoredIds.has(findingId));
    if (targetIds.length === 0) return;

    setAppliedChoices((current) => {
      const next = { ...current };
      for (const findingId of targetIds) {
        next[findingId] = {
          mode: choice.mode,
          depth: choice.mode === "placeholder" ? undefined : choice.depth
        };
      }
      return next;
    });
    setReview(null);
    setStatus(`${targetIds.length}개 항목을 Safe Output에 적용했습니다. 원본 프롬프트는 변경하지 않았습니다.`);
  }

  function updateChoice(findingId: string, patch: Partial<TransformChoice>) {
    setChoices((current) => ({
      ...current,
      [findingId]: { ...(findingChoices[findingId] ?? DEFAULT_CHOICE), ...patch }
    }));
  }

  return (
    <main className="app-shell">
      <header className="app-header">
        <div>
          <p className="eyebrow">Prompt safety preflight</p>
          <h1>Safe Prompt Guard</h1>
          <p>AI에게 보내기 전에 민감정보를 먼저 정리하세요.</p>
        </div>
        <p className="trust-note">원본 프롬프트는 AI 모델에 전송되지 않습니다.</p>
      </header>

      <nav className="workspace-tabs" aria-label="Workspace sections" role="tablist">
        <button
          type="button"
          id="tab-prompt"
          role="tab"
          aria-selected={activeTab === "prompt"}
          aria-controls="panel-prompt"
          className="tab-button"
          onClick={() => setActiveTab("prompt")}
        >
          프롬프트 안전성
          <span>{findings.length > 0 ? `${findings.length}개 탐지` : "검사"}</span>
        </button>
        <button
          type="button"
          id="tab-rules"
          role="tab"
          aria-selected={activeTab === "rules"}
          aria-controls="panel-rules"
          className="tab-button"
          onClick={() => setActiveTab("rules")}
        >
          커스텀 규칙
          <span>{customRules.length > 0 ? `${customRules.length}개 추가` : "생성"}</span>
        </button>
      </nav>

      {activeTab === "prompt" && (
        <div id="panel-prompt" role="tabpanel" aria-labelledby="tab-prompt" className="tab-panel">
          <section className="global-fix-bar" aria-label="Global fix bar">
            <strong>{findings.length > 0 ? `총 ${findings.length}개 위험 요소 발견` : "Scan 대기 중"}</strong>
            <select
              data-testid="global-mode-select"
              value={globalChoice.mode}
              onChange={(event) => setGlobalChoice((current) => ({ ...current, mode: event.target.value as TransformMode }))}
            >
              <option value="masking">마스킹</option>
              <option value="dummy">더미데이터</option>
              <option value="placeholder">플레이스홀더</option>
            </select>
            {globalChoice.mode !== "placeholder" && (
              <select
                data-testid="global-depth-select"
                value={globalChoice.depth}
                onChange={(event) => setGlobalChoice((current) => ({ ...current, depth: event.target.value as TransformDepth }))}
              >
                <option value="partial">부분 변경</option>
                <option value="full">전체 변경</option>
              </select>
            )}
            <button type="button" data-testid="scan-button" onClick={handleScan}>Scan</button>
            <button type="button" data-testid="apply-all-button" onClick={handleApplyAll} disabled={pendingFindings.length === 0}>모두 적용</button>
          </section>

          <section className="workspace" aria-label="Prompt guard workspace">
            <div className="editor-panel">
              <label htmlFor="prompt-input">Prompt</label>
              <textarea id="prompt-input" data-testid="prompt-input" value={sourceText} onChange={(event) => handleSourceTextChange(event.target.value)} />
              <div className="preview-label-row">
                <span id="highlight-preview-label" className="preview-label">검출 결과 미리보기</span>
                <span className="preview-helper">적용한 치환 결과가 이 영역에 반영됩니다.</span>
              </div>
              <div className="highlight-preview" aria-labelledby="highlight-preview-label">
                {renderHighlightedText(sourceText, findings, selectedFinding?.id ?? null, setSelectedFindingId, ignoredFindingIds, appliedChoices)}
              </div>
            </div>

            <aside className="findings-panel" aria-label="Findings panel">
              <h2>Findings</h2>
              {findings.length === 0 && <p>탐지된 위험 요소가 없습니다.</p>}
              {findings.map((finding) => {
                const choice = findingChoices[finding.id] ?? DEFAULT_CHOICE;
                const ignored = ignoredFindingIds.includes(finding.id);
                return (
                  <article className={`finding-card ${selectedFindingId === finding.id ? "selected" : ""} ${appliedChoices[finding.id] ? "applied" : ""}`} key={finding.id}>
                    <div className="finding-card-header">
                      <span className={`severity ${finding.severity}`}>{finding.severity}</span>
                      <strong>{finding.type}</strong>
                      {appliedChoices[finding.id] && <span className="state-pill">applied</span>}
                    </div>
                    <p>{finding.reason}</p>
                    <code>{finding.value}</code>
                    <div className="control-row">
                      <select value={choice.mode} onChange={(event) => updateChoice(finding.id, { mode: event.target.value as TransformMode })}>
                        <option value="masking">마스킹</option>
                        <option value="dummy">더미데이터</option>
                        <option value="placeholder">플레이스홀더</option>
                      </select>
                      {choice.mode !== "placeholder" && (
                        <select value={choice.depth} onChange={(event) => updateChoice(finding.id, { depth: event.target.value as TransformDepth })}>
                          <option value="partial">부분</option>
                          <option value="full">전체</option>
                        </select>
                      )}
                      <select value={choice.scope} onChange={(event) => updateChoice(finding.id, { scope: event.target.value as ApplyScope })}>
                        <option value="selected">이 항목만</option>
                        <option value="same_type">같은 타입 전체</option>
                        <option value="all">모든 위험 요소</option>
                      </select>
                    </div>
                    <div className="button-row">
                      <button type="button" data-testid={`finding-${finding.id}-apply-button`} onClick={() => handleApply(finding)} disabled={ignored}>적용</button>
                      <button type="button" data-testid={`finding-${finding.id}-ignore-button`} onClick={() => handleIgnore(finding)} disabled={ignored}>무시</button>
                    </div>
                  </article>
                );
              })}
            </aside>
          </section>

          <section className="output-panel" aria-label="Safe output preview">
            <div>
              <h2>Safe Output Preview</h2>
              <pre>{safeOutput}</pre>
              <p className="status-line">{status}</p>
            </div>
            <div className="review-panel">
              <div className="button-row">
                <button type="button" data-testid="safe-review-button" onClick={handleSafeReview}>Safe Review</button>
                <button type="button" data-testid="copy-output-button" onClick={handleCopy}>Copy</button>
              </div>
              {review && (
                <div className="review-result">
                  <strong>Safe Review: {review.riskLevel}</strong>
                  <p>{review.summary}</p>
                  <ul>
                    {review.remainingConcerns.map((concern) => <li key={concern}>{concern}</li>)}
                  </ul>
                  <p>{review.recommendation}</p>
                </div>
              )}
            </div>
          </section>
        </div>
      )}

      {activeTab === "rules" && (
        <div id="panel-rules" role="tabpanel" aria-labelledby="tab-rules" className="tab-panel">
          <section className="rule-builder-panel" aria-label="Custom rule builder">
            <div>
              <p className="eyebrow">Custom Rule Builder</p>
              <h2>조직별 패턴 추가</h2>
              <p className="trust-note">실제 secret이나 고객정보를 입력하지 마세요. 형식만 비슷한 더미 예시를 사용하세요.</p>
              <textarea
                data-testid="rule-builder-example-input"
                value={ruleExample}
                onChange={(event) => setRuleExample(event.target.value)}
                aria-label="Rule builder dummy example"
              />
              <div className="button-row">
                <button type="button" data-testid="rule-generate-button" onClick={handleGenerateRule}>Generate Rule</button>
                <button type="button" data-testid="rule-preview-button" onClick={handlePreviewRule} disabled={!generatedRule}>Preview</button>
                <button type="button" data-testid="rule-approve-button" onClick={handleApproveRule} disabled={!generatedRule}>세션에 추가</button>
              </div>
            </div>
            <div className="rule-preview-card">
              <h3>Rule Preview</h3>
              {generatedRule ? (
                <>
                  <dl>
                    <dt>type</dt>
                    <dd>{generatedRule.rule.type}</dd>
                    <dt>pattern</dt>
                    <dd><code>{generatedRule.rule.pattern}</code></dd>
                    <dt>replacement</dt>
                    <dd><code>{generatedRule.rule.replacement}</code></dd>
                    <dt>source</dt>
                    <dd>{generatedRule.source}</dd>
                  </dl>
                  {generatedRule.warnings.map((warning) => <p className="warning" key={warning}>{warning}</p>)}
                  <p>{generatedRule.falsePositiveRisk}</p>
                  <p>{generatedRule.falseNegativeRisk}</p>
                  {rulePreview && (
                    <div className="review-result">
                      <strong>{rulePreview.matched ? "Matched" : "No match"}</strong>
                      <pre>{rulePreview.transformedText}</pre>
                    </div>
                  )}
                  <p className="status-line">Session custom rules: {customRules.length}</p>
                </>
              ) : (
                <p>더미 예시로 rule 후보를 생성하세요.</p>
              )}
            </div>
          </section>
        </div>
      )}
    </main>
  );
}

function renderHighlightedText(
  text: string,
  findings: Finding[],
  selectedFindingId: string | null,
  onSelect: (findingId: string) => void,
  ignoredFindingIds: string[],
  appliedChoices: Record<string, AppliedTransformChoice>
) {
  if (findings.length === 0) return <span>{text}</span>;

  const nodes: ReactNode[] = [];
  let cursor = 0;

  findings.forEach((finding) => {
    if (cursor < finding.start) {
      nodes.push(<span key={`text-${cursor}`}>{text.slice(cursor, finding.start)}</span>);
    }
    const displayValue = getFindingDisplayValue(finding, appliedChoices);
    nodes.push(
      <button
        type="button"
        key={finding.id}
        className={`highlight ${finding.severity} ${selectedFindingId === finding.id ? "selected" : ""} ${ignoredFindingIds.includes(finding.id) ? "ignored" : ""} ${appliedChoices[finding.id] ? "applied" : ""}`}
        onClick={() => onSelect(finding.id)}
      >
        {displayValue}
      </button>
    );
    cursor = finding.end;
  });

  if (cursor < text.length) {
    nodes.push(<span key={`text-${cursor}`}>{text.slice(cursor)}</span>);
  }

  return nodes;
}